### ISSUE TITLE
Wrong rpath when run as localhost

### ISSUE THREAD

**Issue by cristianolongo** [mappiamo/mapi-geoCMS#14]
I downloaded and run mapi-geoCMS in the user directory of the local web server, using the eclipse debugger. The url is

http://localhost/~cristiano/mapi-geoCMS/manager?XDEBUG_SESSION_START=ECLIPSE_DBGP&KEY=14393312835233

With the debugger I observe that the $rpath variable in index.php has the value "no/public_html/mapi-geoCMS/manager"

I can't know which is the expected value for this variable, and the effects of this issue. However I can't login and this should be related.

**Comment by sabas** [comment]
Ciao Cristiano,
could you try to modify index.php and manager/index.php in this line

```
$rpath = substr( dirname( __FILE__ ), strlen( $_SERVER['DOCUMENT_ROOT'] ) );
```

with something like this
https://gist.github.com/sabas/0d2683371f0d3147e5cf

calling `$rpath=magicpath(0);`

**Comment by cristianolongo** [comment]
I got "http://localhostno/public_html/mapi-geoCMS/"

**Comment by cristianolongo** [comment]
I set up a VirtualHost in my local web server and this issue does not occur in this way.

**Comment by sabas** [comment]
I think the problem is the tilde in the path, you're using apache?

edit: https://www.cs.tut.fi/~jkorpela/tilde.html

**Comment by CosmicLaca** [comment]
I think solved.
