### ISSUE TITLE
Leaflet.draw cannot edit saved data

### ISSUE THREAD

**Issue by CosmicLaca** [mappiamo/mapi-geoCMS#19]
The problem is on the file: manager\modules\mcontent\views\edit.php started on row: 242.

Problem details:
- If I use WKT Parser to read saved data from database (row: 243) Leaflet displays geoms correctly, but I cannot edit result with leaflet.draw. The geoms placed to right layer (named: "draw_layer") using row 269 and 270. I think the problem is, that the saved polygons not indexed for leaflet.draw just display for leaflet. If create new lines with draw, the saved data can be edited and deleted (I think the new index have same value), but before insert new line or polygon, cannot edit new data with .draw.
- If I use another method (now commented on source code, using rows: 249 and 272) the saved lines deletable and editable with draw, but the latitude longitude pairs must be changed for correct displays.

---

Looking for solutions to read and display saved data, and edit same data with leaflet.draw at same interface.  For WKT.parser() data have to be indexed (but how?), or using another method L.polyline(x_Geoms).addTo(draw_layer); the lan/lot data must be changed to lon/lat (on client side).

**Comment by sabas** [comment]
x_Geoms = L.geoJson(geoj);
The geojson layer in leaflet extends the featuregroup layer. Imo you have to convert the geojson to featuregroup
So the idea would be to use the commented method, swapping the coordinates (http://jsperf.com/switch-elements). It's a linear operation [O(n)], so it should be feasible

**Comment by CosmicLaca** [comment]
To swapping coordinates I think is very dirty solution for unknown size GEOMETRYCOLLECTION(), so I dont wanna use it.

The feature group conversion not succeed or I dont know how to do it. I created layer for leaflet.daw on previously included .js like this:
var draw_layer = L.featureGroup().addTo(map);

**Comment by sabas** [comment]
What about something like

```
var draw_layer = L.featureGroup().addTo(map);
function moveToFeatureGroup (feature, layer){
layer.addTo(draw_layer);
}
x_Geoms = L.geoJson(geoj, {onEachFeature: moveToFeatureGroup});
```

**Comment by CosmicLaca** [comment]
Thank you! I trying / testing this method, and I have result.

**Comment by CosmicLaca** [comment]
Thank you, this is good solution, uploading the first version for testing
