### ISSUE TITLE
Limit decimals in coordinates

### ISSUE THREAD

**Issue by sabas** [mappiamo/mapi-geoCMS#4]
http://en.wikipedia.org/wiki/Decimal_degrees
6 / 7 decimals should be sufficent...

**Comment by CosmicLaca** [comment]
We now using geoms like multilinestring etc. not only latitude and longitude or point() as input. Sometime we got these data from outside database, sometime we using leaflet draw (what we use to re-read lines and areas). I think to reduce all decaimals on large geometry data is not worth.
